### PR TITLE
Branch find command

### LINKED ISSUE #47: As a user ready to use the app, I want to be able to categorise the module for a flashcard that I have already created

### PR DESCRIPTION
**Pull request by joshtyf**
Implemented `find` command functionality to search for `Flashcard` by their tags

### CODE REVIEW

**Review by josiahkhoo — APPROVED** [review]
LGTM! 👍

**Comment by joshtyf** [comment]
Let me update the UG for the `find` command first before merging the PR

**Comment by joshtyf** [comment]
UserGuide updated. Ready for review and merge

**Comment by ChenXJ98** [comment]
lgtm! thank you!

**Pull request merged**
