### PR TITLE
Add Open Flashcard Activity Diagram

### LINKED ISSUE #279: Add activity diagrams to DG
Adding new flashcards mcq and oeq (Gilbert)
Open flashcards (XJ)
Delete by index and delete by tag (Josh)
Finding flashcards and editing flashcards(Josiah)
Display and clear stats (Francis)

### PR DESCRIPTION
**Pull request by ChenXJ98**

### CODE REVIEW

**Review by GilbertTan19 — CHANGES_REQUESTED** [review]
For the openFlashcard might need some change like the one josh send

**Review by josiahkhoo — APPROVED** [review]
LGTM!

**Review by GilbertTan19 — APPROVED** [review]
LGTM!

**Review by joshtyf — APPROVED** [review]
LGTM!

**Pull request merged**
