### PR TITLE
Update developer guide for add, addmcq and delete command

### LINKED ISSUE #144: Add preface to the quick start section of UG
Provide a quick start demo with pictures

### PR DESCRIPTION
**Pull request by GilbertTan19**

### CODE REVIEW

**Comment by ChenXJ98** [comment]
Looks good! I will review it after lunch!

**Review by joshtyf — CHANGES_REQUESTED** [review]
Everything looks good except that I think the arguments for the `parse` method in the sequence diagrams should have `""`.
i.e. it should be `parseCommand("add q/question ans/ Answer")` instead of just `parseCommand(add q/question ans/ Answer)`

**Comment by FH-30** [comment]
> Everything looks good except that I think the arguments for the `parse` method in the sequence diagrams should have `""`.
> i.e. it should be `parseCommand("add q/question ans/ Answer")` instead of just `parseCommand(add q/question ans/ Answer)`

From the diagrams in addressbook's documentation and the test command documentation, they don't seem to be using the `""`. I'm not so sure whether it would be best to follow their practices though.

**Comment by FH-30** [comment]
The diagram looks good, however I think that the AddOpenEndedQuestionCommand should have a cross indicating that it is no longer referenced after the execute() method is called on it.

**Comment by GilbertTan19** [comment]
I'll do it in another branch, cause I try to solve the conflict locally but cannot push to my repo.

**Pull request closed without merging**
